default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rcalendar_development

test:
  <<: *default
  database: rcalendar_test

production:
  <<: *default
